### ISSUE TITLE
I think nwbuild gets zombified after first use on WSL

### ISSUE THREAD

**Issue by lukaszkups** [nwutils/nw-builder#523] opened 2020-01-04 20:29 UTC
I'm using WSL on Windows 10. First run of build command (`nwbuild`) works just fine, but after that I think it keeps running in the background as I can't remove (not via UI or command line) `build` folder (also if I try do it via Visual Studio Code file explorer it seems like folder is being removed at first, but once I click on refresh icon the folder is being shown back).

I've tried to find and kill it via task manager or `ps aux` command, but without success.

After system reboot, it works again only on first try.

**Comment by ayushmxn** [comment] 2022-07-26 23:45
Turns out we don't [kill the child process](https://stackoverflow.com/a/32263232/11697814) anywhere. I use WSL so I have experienced this myself (only few days ago!). Can't see why it shouldn't be happening in other OSs.

**Comment by ayushmxn** [comment] 2022-08-05 08:05
https://github.com/nodejs/node/issues/13538
I'm actually not sure how to go about this. Since this has only happened to me once and I have not been able to consistently reproduce, closing this for now.

**Closed by ayushmxn** 2022-08-05 08:05 UTC
Labels: bug, t-1
