### ISSUE TITLE
No support for CommonJS

### ISSUE THREAD

**Issue by indexofrefraction** [nwutils/nw-builder#696] opened 2022-11-20 09:24 UTC
hi, 

i'm using nw-builder inside a macos node js shell command "nwbuild".
since 4.0.0 var NwBuilder = require('nw-builder'); is not supported anymore (Error ERR_REQUIRE_ESM)
but if i add type: "module" to the package.json and change to: import { nwbuild } from 'nw-builder';
i get Error ERR_UNKNOWN_FILE_EXTENSION because im running "nwbuild" without extension

**is there a way around changing the commands name to nwbuild.js ?**

if i do and replace: 
```
#!/usr/bin/env node
var NwBuilder = require('nw-builder');
var settings = {
	files: '_build/\*\*/\*\*',
	platforms: ['osx64', 'win32'], flavor: 'normal', version: 'latest', 
	buildDir: '_nwbuild',  cacheDir: '_nwcache', zip: true
}
var nw = new nwbuild(settings); 
nw.build().then(function () {
	console.log("Promise Resolved");
}).catch(function () {
	console.log("Promise Rejected");
});
```
by
```
#!/usr/bin/env node
import { nwbuild } from 'nw-builder';
var settings = {
	srcDir: "_build",
	platform: 'osx', arch: 'x64', flavor: 'normal', version: 'latest',
	outDir: '_nwbuild', cacheDir: '_nwcache', zip: true
};
nwbuild(settings).then(function () {
	console.log("Promise Resolved");
}).catch(function () {
	console.log("Promise Rejected");
});
```
i get this :
% nwbuild_test.js 
[ INFO ] Manifest file already exists locally under _nwcache
 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% | ETA: 0s | 22833/22833
Promise Rejected

**a small porting guide from 3.x to 4.x would be nice**
what is the problem with the code?
do the platforms need to be built separately now?
what about arm64 / universal on osx?

**Comment by sysrage** [comment] 2022-11-20 14:27
I just encountered this myself and was annoyed that CJS wasn't supported (especially since NW.js doesn't support ESM for the `main` script). I've updated the Issue title and I'm hijacking this Issue to request that CJS be supported. I don't have specifics handy, but it's possible for a package to support both ESM and CJS out-of-the-box.

That said @indexofrefraction, you can simply name your build script with the `.mjs` extension and it'll be treated as an ESM module by Node.js. That way, you don't need to include `"type": "module"` in `package.json`, which wouldn't be accurate for your NW.js script.

Additionally, I do have this working, so you should log your error to see what the problem is:
```js
nwbuild(settings).then(function () {
	console.log("Promise Resolved");
}).catch(function (error) {
	console.log("Promise Rejected", error);
});
```

It's possible you're running into Issue #692, but I don't think that was rejecting (just never resolving).

**Comment by sysrage** [comment] 2022-11-20 14:31
As an aside, I also ran into the issue of only one platform being supported. I suggest opening a separate issue to track that request, if it's important. As you can see in the `dist.mjs` script in `nw-react`, I just work around this by calling `nwbuild()` multiple times. This ultimately works out better, so I can change file/directory names and application content depending on the platform.

**Comment by indexofrefraction** [comment] 2022-11-20 17:01
hi, 
tx for tip about the mjs extension. (but I wish i wouldn't need that / run it without extension) 
LOL, and the error i get is just : 1

**Comment by sysrage** [comment] 2022-11-20 18:02
Ya, the error only being "1" makes sense (but should also be fixed):
- https://github.com/nwutils/nw-builder/blob/main/src/bld/compress.js#L31
- https://github.com/nwutils/nw-builder/blob/main/src/bld/compress.js#L38

@tharatau, you should probably be calling `reject(error)` instead of `reject(1)` in both these spots. The values you're returning with `reject()` and `resolve()` aren't very helpful.

**Comment by indexofrefraction** [comment] 2022-11-20 18:18
maybe to add... if the cache is cleared, the above script downloads manifest.json and nw.zip
and then exits with "[ INFO ] Manifest file already exists locally under _nwcache" and error 1

**Comment by sysrage** [comment] 2022-11-21 02:21
Your fix for this isn't how ESM/async works. Example:

```js
const { nwbuild } = require('nw-builder');

console.log('nwbuild', nwbuild);
```

You will see `nwbuild undefined` in the console, because the exported variable is undefined until the async IIFE in `nwbuild.cjs` resolves. Obviously, attempting to call `nwbuild()` also fails.

There are ways to support both CJS and ESM, but this isn't right. I believe you need to use a bundler to have the scripts built as ESM/CJS, but I'm not sure.

**Comment by tharatau** [comment] 2022-11-21 05:12
> i'm using nw-builder inside a macos node js shell command "nwbuild".

If you're using it via a shell command, maybe the [`nwbuild` CLI command (https://github.com/nwutils/nw-builder/blob/3090addc3931c3ab5edea0e5afccfe613ed63b24/package.json#L28) may be a better fit.

> since 4.0.0 var NwBuilder = require('nw-builder'); is not supported anymore (Error ERR_REQUIRE_ESM)

Apologies for this, oversight on my part. Temporary workaround would be using [`import()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)

> a small porting guide from 3.x to 4.x would be nice

I'm working on documentation and adding a migration guide [here](https://nwutils.io/nw-builder/) but it far from complete.

> what is the problem with the code?

I will try to reproduce on my end.

> do the platforms need to be built separately now?

v4 `nwbuild` function focuses on doing one build. I find this to be more intuitive and easier to debug/test.

> what about arm64 / universal on osx?

Officially only x64 build is supported right now. More info on that here: https://github.com/nwjs/nw.js/issues/7620

**Comment by tharatau** [comment] 2022-11-21 05:14
> Your fix for this isn't how ESM/async works. Example:
> 
> ```js
> const { nwbuild } = require('nw-builder');
> 
> console.log('nwbuild', nwbuild);
> ```
> 
> You will see `nwbuild undefined` in the console, because the exported variable is undefined until the async IIFE in `nwbuild.cjs` resolves. Obviously, attempting to call `nwbuild()` also fails.
> 
> There are ways to support both CJS and ESM, but this isn't right. I believe you need to use a bundler to have the scripts built as ESM/CJS, but I'm not sure.

Yeah my bad I definitily I did this in haste without testing thoroughly. I'll look into the bundler solution.

**Comment by indexofrefraction** [comment] 2022-11-21 20:38
remark:
my settings above failed because using version:"latest" doesn't work !
with "0.70.1" the build starts (promise resolved)
the app doesn't run, there is no app.nw but at least something happens .-)

**Closed** 2022-11-26 04:13 UTC
Labels: bug
