### ISSUE TITLE
SyntaxError: The requested module 'node:fs/promises' does not provide an export named 'constants'

### ISSUE THREAD

**Issue by MistakingManx** [nwutils/nw-builder#736] opened 2022-12-22 17:15 UTC
### Issue Type
- [ ] Bug?

### Current/Missing Behaviour
```
import { access, constants, readFile, rm } from "node:fs/promises";
                 ^^^^^^^^^
SyntaxError: The requested module 'node:fs/promises' does not provide an export named 'constants'
```
This error is displayed, I'd use the cli version, but my NPM doesn't make commands globally usable.

### Expected/Proposed Behaviour
it to work

### Additional Info
I don't usually work with ESM, I tried using Common JS, but it was just erroring with 1 so I couldn't figure out what was wrong.
I tried to make an ESM script, but this was the error, and using import() from Common JS yielded the same error.

- Operating System: Windows
- Node version: v17.0.1
- NW.js version: 0.68.0

**Comment by MistakingManx** [comment] 2022-12-22 17:19
I tested a little tiny bit and importing "fs" gave me the constants, but "node:fs/promises" did not.
is this a Node.JS version problem then?

**Comment by MistakingManx** [comment] 2022-12-22 17:29
Switching to the version stated `14.19` gave another error about `cp` not being apart of `fs/promises`.
What version should I use?

**Comment by tharatau** [comment] 2022-12-23 01:38
Hello! The current stable version for nw-builder is [v3.8.6](https://github.com/nwutils/nw-builder/tree/v3.8.6). I'll put this in the docs so its known. The syntax error has been fixed in git. I'm working on #729 after which I'll probably make a minor release. I'd suggest using the stable version for now though, apologies for the confusion!

**Comment by MistakingManx** [comment] 2023-01-20 18:04
I ended up switching between versions until one of them worked, I think it was Node v19, but I mix numbers up really easy.

**Comment by aztack** [comment] 2023-05-29 07:12
4.2.3 still have this syntax error:
<img width="827" alt="image" src="https://github.com/nwutils/nw-builder/assets/782871/5c0ca092-4888-4ce8-928a-4dbfdcf280de">

**Comment by A9U3HC** [comment] 2023-05-29 07:48
I realise what the problem is now:

1. nw-builder assumes you should have the latest Node.js installed which should not be the case. Node 16 should still be supported.
2. The way command line args are parsed, invalid args are ignored (read: people using v3 syntax for v4). In this case the default args are used. Combine that with [1] and we have a weird developer experience.

**Comment by TheJaredWilcurt** [comment] 2023-05-29 14:38
> "Maintenance, current, and latest should all be supported" - A9U3HC

Each library maintainer can pick and choose what their library does and doesn't support. You can use a Node Version Manager to switch to different versions. You'll find the least trouble with NW.js (and really all technology related to JavaScript) by sticking with the latest versions of everything. But specifically making sure your global Node.js version matches the version built in to NW.js.

OS         | [Nodist](https://github.com/nullivex/nodist) | [nvm-windows](https://github.com/coreybutler/nvm-windows) | [nvm](https://github.com/nvm-sh/nvm) | [Volta](https://volta.sh)
:--        | :--:   | :--:        | :--: | :--:
Windows 7  | X      |             |      | X
Windows 8  |        |             |      | X
Windows 10 |        | X           |      | X
Windows 11 |        | X           |      | X
Linux      |        |             | X    | X
OSX        |        |             | X    | X

The last NW.js version with Node 14 support was 0.49.1 (from October 2020). You would be best off switching to the latest version of NW.js (0.76.1) and installing the same version of Node.js globally (20.1.0).

There are some [legitimate reasons](https://dev.to/thejaredwilcurt/guide-to-nw-js-versions-5d38) to use older versions of NW.js. And maybe you have one. Others might too. Ideally `nw-builder` would work with all versions of NW.js and Node. But for such a complex task as automated building of a desktop app, that is a very tall order. Unfortunately there are many parts of the Node.js API that only run in certain ranges of Node versions. So there can be no one singular codebase that works perfectly in all versions, and even if we attempted, it would mean giving up any use of dependencies to solve common problems (like downloading and unzipping a file, etc).

If there is a way to transpile newer Node to older version we could try that, but the only option I know of is Babel, and it doesn't work for [the supplied code](https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzgQwMaoKYGcsBo6oQB2WMyRMecUGyAJgGLAA2G-UIcAvnAGZQROAciIQ6GAFy8sAejACQwLNiEBuAFDrCJCKwB0zCAHMAFEjSYc-baXKV2tRizbVOXAJQagA&debug=false&forceAllTransforms=true&modules=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Ces2016%2Ces2015-loose&prettier=false&targets=Node-14&version=7.22.2&externalPlugins=&assumptions={}).

The `node:` prefix was not added until Node 18, but the transpiler does not convert it to older approach, so the code it generates would just throw this error:

> Uncaught Error: Cannot find module 'node:fs/promises'

## Recommendations

**Option 1: Stick to the latest**

1. Uninstall Node.js, reboot, delete all remaining Node references (appData, program files, etc)
1. Install one of the Node version managers linked above
1. Use it to install Node.js v20.1.0
1. Update your project to use NW.js v0.76.1
1. Routinely update your dependencies and when you need to update NW.js, also update to the same Node.js version
   * You can find all details of NW.js and Node version here:
   * https://nwjs.io/versions.json

**Option 2: Write your own custom build script**

Depending on your project's needs you may be able write a build script that `npm install`'s using an older version of Node that matches your older NW.js version. Then store that `node_modules` folder in a safe place. Then it switches Node versions to use a newer option and then uses `nw-builder` to do all the heavy lifting, then at the end swap out the `node_modules` folder in the built version with your original copy generated with your older node version.

Or you may need to abandon use of `nw-builder` with your project and write your own custom build script entirely from scratch. This has been the approach most of the community has taken for years. However, if whatever is preventing you from updating to the latest NW.js version ever changes you can then switch back and re-adopt `nw-builder`.

**Closed by TheJaredWilcurt** 2023-05-29 14:38 UTC
Labels: bug
